### ISSUE TITLE
Battery Characteristics

### ISSUE THREAD

**Issue by Bgoczan** [legokor/UPRA-EPS#1]
## Measure: 
- [x] Single AA cell characteristics: #2
- [x] 4xAA cell characteristics: #3
- [x] 3xAA cell characteristics: #4
- [x] Single AAA cell characteristics: #5
- [ ] 4xAAA cell characteristics: #6
- [ ] 3xAAA cell characteristics: #7
- [ ] Single 3.7V LiPo cell characteristics: #8
- [ ] 2x 3.7V LiPo cell characteristics: #9

## Documentation
All results shall be documented in [Battery Characteristics wiki page](https://github.com/legokor/UPRA-EPS/wiki/Battery-Characteristics)

## Completion rule
All related issues shall be closed: Issue #2, Issue #3, Issue #4, Issue #5, Issue #6, Issue #7, Issue #8, Issue #9
